//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DANGKY
    {
        [Key, Column(Order = 0)]
        public string MaSV { get; set; }
        [Key, Column(Order = 1)]
        public string MaLHP { get; set; }
        public Nullable<int> DiemChuyenCan { get; set; }
        public Nullable<int> DiemGiuaKy { get; set; }
        public Nullable<int> DiemCuoiKy { get; set; }
    
        public virtual LOPHOCPHAN LOPHOCPHAN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
