//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnEntities : DbContext
    {
        public DoAnEntities()
            : base("name=DoAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_ACCOUNT> ADMIN_ACCOUNT { get; set; }
        public virtual DbSet<DANGKY> DANGKY { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIEN { get; set; }
        public virtual DbSet<KHOA> KHOA { get; set; }
        public virtual DbSet<LOPHOCPHAN> LOPHOCPHAN { get; set; }
        public virtual DbSet<MONHOC> MONHOC { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIEN { get; set; }
    }
}
